//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Query.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class QueryLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		AND=1, OR=2, EQUALS=3, CONTAINS=4, NAME=5, STRING=6, INTEGER=7, DOUBLE=8, 
		LPAREN=9, RPAREN=10, COMMA=11, WS=12;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"AND", "OR", "EQUALS", "CONTAINS", "NAME", "STRING", "INTEGER", "DOUBLE", 
		"DIGIT", "LPAREN", "RPAREN", "COMMA", "WS"
	};


	public QueryLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public QueryLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, "'('", "')'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "AND", "OR", "EQUALS", "CONTAINS", "NAME", "STRING", "INTEGER", 
		"DOUBLE", "LPAREN", "RPAREN", "COMMA", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Query.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static QueryLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,12,105,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,
		6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,1,0,1,0,1,0,1,
		0,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,3,1,3,1,3,1,3,1,3,1,3,1,3,
		1,3,1,3,1,4,4,4,52,8,4,11,4,12,4,53,1,5,1,5,1,5,1,5,5,5,60,8,5,10,5,12,
		5,63,9,5,1,5,1,5,1,6,3,6,68,8,6,1,6,4,6,71,8,6,11,6,12,6,72,1,7,3,7,76,
		8,7,1,7,4,7,79,8,7,11,7,12,7,80,1,7,1,7,4,7,85,8,7,11,7,12,7,86,3,7,89,
		8,7,1,8,1,8,1,9,1,9,1,10,1,10,1,11,1,11,1,12,4,12,100,8,12,11,12,12,12,
		101,1,12,1,12,0,0,13,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,0,19,9,21,10,
		23,11,25,12,1,0,17,2,0,65,65,97,97,2,0,78,78,110,110,2,0,68,68,100,100,
		2,0,79,79,111,111,2,0,82,82,114,114,2,0,69,69,101,101,2,0,81,81,113,113,
		2,0,85,85,117,117,2,0,76,76,108,108,2,0,83,83,115,115,2,0,67,67,99,99,
		2,0,84,84,116,116,2,0,73,73,105,105,3,0,48,57,65,90,97,122,2,0,34,34,92,
		92,1,0,48,57,3,0,9,10,13,13,32,32,113,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,
		0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,19,
		1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,0,1,27,1,0,0,0,3,31,1,0,0,
		0,5,34,1,0,0,0,7,41,1,0,0,0,9,51,1,0,0,0,11,55,1,0,0,0,13,67,1,0,0,0,15,
		75,1,0,0,0,17,90,1,0,0,0,19,92,1,0,0,0,21,94,1,0,0,0,23,96,1,0,0,0,25,
		99,1,0,0,0,27,28,7,0,0,0,28,29,7,1,0,0,29,30,7,2,0,0,30,2,1,0,0,0,31,32,
		7,3,0,0,32,33,7,4,0,0,33,4,1,0,0,0,34,35,7,5,0,0,35,36,7,6,0,0,36,37,7,
		7,0,0,37,38,7,0,0,0,38,39,7,8,0,0,39,40,7,9,0,0,40,6,1,0,0,0,41,42,7,10,
		0,0,42,43,7,3,0,0,43,44,7,1,0,0,44,45,7,11,0,0,45,46,7,0,0,0,46,47,7,12,
		0,0,47,48,7,1,0,0,48,49,7,9,0,0,49,8,1,0,0,0,50,52,7,13,0,0,51,50,1,0,
		0,0,52,53,1,0,0,0,53,51,1,0,0,0,53,54,1,0,0,0,54,10,1,0,0,0,55,61,5,34,
		0,0,56,57,5,92,0,0,57,60,9,0,0,0,58,60,8,14,0,0,59,56,1,0,0,0,59,58,1,
		0,0,0,60,63,1,0,0,0,61,59,1,0,0,0,61,62,1,0,0,0,62,64,1,0,0,0,63,61,1,
		0,0,0,64,65,5,34,0,0,65,12,1,0,0,0,66,68,5,45,0,0,67,66,1,0,0,0,67,68,
		1,0,0,0,68,70,1,0,0,0,69,71,3,17,8,0,70,69,1,0,0,0,71,72,1,0,0,0,72,70,
		1,0,0,0,72,73,1,0,0,0,73,14,1,0,0,0,74,76,5,45,0,0,75,74,1,0,0,0,75,76,
		1,0,0,0,76,78,1,0,0,0,77,79,3,17,8,0,78,77,1,0,0,0,79,80,1,0,0,0,80,78,
		1,0,0,0,80,81,1,0,0,0,81,88,1,0,0,0,82,84,5,46,0,0,83,85,3,17,8,0,84,83,
		1,0,0,0,85,86,1,0,0,0,86,84,1,0,0,0,86,87,1,0,0,0,87,89,1,0,0,0,88,82,
		1,0,0,0,88,89,1,0,0,0,89,16,1,0,0,0,90,91,7,15,0,0,91,18,1,0,0,0,92,93,
		5,40,0,0,93,20,1,0,0,0,94,95,5,41,0,0,95,22,1,0,0,0,96,97,5,44,0,0,97,
		24,1,0,0,0,98,100,7,16,0,0,99,98,1,0,0,0,100,101,1,0,0,0,101,99,1,0,0,
		0,101,102,1,0,0,0,102,103,1,0,0,0,103,104,6,12,0,0,104,26,1,0,0,0,11,0,
		53,59,61,67,72,75,80,86,88,101,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
