//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Query.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="QueryParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IQueryListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery([NotNull] QueryParser.QueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery([NotNull] QueryParser.QueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] QueryParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] QueryParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.binaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryOp([NotNull] QueryParser.BinaryOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.binaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryOp([NotNull] QueryParser.BinaryOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOp([NotNull] QueryParser.UnaryOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOp([NotNull] QueryParser.UnaryOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.nameToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameToken([NotNull] QueryParser.NameTokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.nameToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameToken([NotNull] QueryParser.NameTokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.valueToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueToken([NotNull] QueryParser.ValueTokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.valueToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueToken([NotNull] QueryParser.ValueTokenContext context);
}
