name: Docker Image CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --platform linux/arm64 --file ./Issueneter.WebAPI/Dockerfile --tag hrrrrustic/issueneterwebapi:$(date +%s)
